
/**************************************************************
 *	
 *	airDinoDeath, 8 bit, 8000Hz,
 *	1 channel, 9670 bytes/channel
 *	Total Size: 1 * 9670 + 4 (header) = 9714 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\airDinoDeath.wav
 *	Time-stamp: Thu Apr 11 00:20:43 2013
 *	
 **************************************************************/

#ifndef __AIRDINODEATHH__
#define __AIRDINODEATHH__

#define AIRDINODEATHFREQ 8000
#define AIRDINODEATHLEN 9670

extern const unsigned char airDinoDeath[9670];

#endif /* __AIRDINODEATHH__ */
