
/**************************************************************
 *	
 *	arrowSound, 8 bit, 48000Hz,
 *	1 channel, 23663 bytes/channel
 *	Total Size: 1 * 23663 + 4 (header) = 23707 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\WAV2C\arrowSound.wav
 *	Time-stamp: Tue Apr 09 00:24:11 2013
 *	
 **************************************************************/

#ifndef __ARROWSOUNDH__
#define __ARROWSOUNDH__

#define ARROWSOUNDFREQ 48000
#define ARROWSOUNDLEN 23663

extern const unsigned char arrowSound[23663];

#endif /* __ARROWSOUNDH__ */
