
/**************************************************************
 *	
 *	bgMusic, 8 bit, 44100Hz,
 *	1 channel, 4630500 bytes/channel
 *	Total Size: 1 * 4630500 + 4 (header) = 4630544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\WAV2C\bgMusic.wav
 *	Time-stamp: Tue Apr 09 00:08:59 2013
 *	
 **************************************************************/

#ifndef __BGMUSICH__
#define __BGMUSICH__

#define BGMUSICFREQ 44100
#define BGMUSICLEN 4630500

extern const unsigned char bgMusic[4630500];

#endif /* __BGMUSICH__ */
