
/**************************************************************
 *	
 *	bgMusic2, 8 bit, 48000Hz,
 *	1 channel, 4630500 bytes/channel
 *	Total Size: 1 * 4630500 + 4 (header) = 4630544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\WAV2C\bgMusic2.wav
 *	Time-stamp: Sun Apr 21 03:44:42 2013
 *	
 **************************************************************/

#ifndef __BGMUSIC2H__
#define __BGMUSIC2H__

#define BGMUSIC2FREQ 48000
#define BGMUSIC2LEN 4630500

extern const unsigned char bgMusic2[4630500];

#endif /* __BGMUSIC2H__ */
