
/**************************************************************
 *	
 *	bossMusic, 8 bit, 44100Hz,
 *	1 channel, 3748500 bytes/channel
 *	Total Size: 1 * 3748500 + 4 (header) = 3748544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\bossMusic.wav
 *	Time-stamp: Mon Apr 22 10:21:47 2013
 *	
 **************************************************************/

#ifndef __BOSSMUSICH__
#define __BOSSMUSICH__

#define BOSSMUSICFREQ 44100
#define BOSSMUSICLEN 3748500

extern const unsigned char bossMusic[3748500];

#endif /* __BOSSMUSICH__ */
