
/**************************************************************
 *	
 *	clink, 8 bit, 44100Hz,
 *	1 channel, 220500 bytes/channel
 *	Total Size: 1 * 220500 + 4 (header) = 220544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\WAV2C\clink.wav
 *	Time-stamp: Mon Apr 22 05:35:19 2013
 *	
 **************************************************************/

#ifndef __CLINKH__
#define __CLINKH__

#define CLINKFREQ 44100
#define CLINKLEN 220500

extern const unsigned char clink[220500];

#endif /* __CLINKH__ */
