
/**************************************************************
 *	
 *	explode, 8 bit, 44100Hz,
 *	1 channel, 220500 bytes/channel
 *	Total Size: 1 * 220500 + 4 (header) = 220544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\WAV2C\explode.wav
 *	Time-stamp: Mon Apr 22 05:35:16 2013
 *	
 **************************************************************/

#ifndef __EXPLODEH__
#define __EXPLODEH__

#define EXPLODEFREQ 44100
#define EXPLODELEN 220500

extern const unsigned char explode[220500];

#endif /* __EXPLODEH__ */
