
/**************************************************************
 *	
 *	gunshot, 8 bit, 22050Hz,
 *	1 channel, 220500 bytes/channel
 *	Total Size: 1 * 220500 + 4 (header) = 220544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\WAV2C\gunshot.wav
 *	Time-stamp: Sun Apr 21 03:43:56 2013
 *	
 **************************************************************/

#ifndef __GUNSHOTH__
#define __GUNSHOTH__

#define GUNSHOTFREQ 22050
#define GUNSHOTLEN 220500

extern const unsigned char gunshot[220500];

#endif /* __GUNSHOTH__ */
