
/**************************************************************
 *	
 *	menuMusic, 8 bit, 44100Hz,
 *	1 channel, 5071500 bytes/channel
 *	Total Size: 1 * 5071500 + 4 (header) = 5071544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\WAV2C\menuMusic.wav
 *	Time-stamp: Mon Apr 22 09:42:46 2013
 *	
 **************************************************************/

#ifndef __MENUMUSICH__
#define __MENUMUSICH__

#define MENUMUSICFREQ 44100
#define MENUMUSICLEN 5071500

extern const unsigned char menuMusic[5071500];

#endif /* __MENUMUSICH__ */
