
/**************************************************************
 *	
 *	pirateDeath, 8 bit, 11025Hz,
 *	1 channel, 4773 bytes/channel
 *	Total Size: 1 * 4773 + 4 (header) = 4817 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\WAV2C\pirateDeath.wav
 *	Time-stamp: Sun Apr 21 03:43:53 2013
 *	
 **************************************************************/

#ifndef __PIRATEDEATHH__
#define __PIRATEDEATHH__

#define PIRATEDEATHFREQ 11025
#define PIRATEDEATHLEN 4773

extern const unsigned char pirateDeath[4773];

#endif /* __PIRATEDEATHH__ */
