
/**************************************************************
 *	
 *	raptorDeath, 8 bit, 44100Hz,
 *	1 channel, 220500 bytes/channel
 *	Total Size: 1 * 220500 + 4 (header) = 220544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\WAV2C\raptorDeath.wav
 *	Time-stamp: Tue Apr 09 11:34:29 2013
 *	
 **************************************************************/

#ifndef __RAPTORDEATHH__
#define __RAPTORDEATHH__

#define RAPTORDEATHFREQ 44100
#define RAPTORDEATHLEN 220500

extern const unsigned char raptorDeath[220500];

#endif /* __RAPTORDEATHH__ */
