
/**************************************************************
 *	
 *	victory, 8 bit, 44100Hz,
 *	1 channel, 220500 bytes/channel
 *	Total Size: 1 * 220500 + 4 (header) = 220544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\echuchee\Desktop\victory.wav
 *	Time-stamp: Mon Apr 22 10:33:35 2013
 *	
 **************************************************************/

#ifndef __VICTORYH__
#define __VICTORYH__

#define VICTORYFREQ 44100
#define VICTORYLEN 220500

extern const unsigned char victory[220500];

#endif /* __VICTORYH__ */
